Translation from martinascholger/TEI
TEIC/TEI pull request #2202
Opened 2021-10-25 12:14 UTC by martinascholger

2022-01-05 14:20 UTC, sabineseifert requested changes
Thanks for the pull requests. See individual comments for requested changes.

2022-01-05 14:20 UTC, sabineseifert commented on P5/Source/Specs/acquisition.xml
> +  <gloss xml:lang="de" versiondate="2021-10-24">enthält Informationen über den Vorgang, durch den ein Manuskript, ein Manuskriptteil oder ein anderes Objekt in den Besitz einer Institution gelangt is
That should be `<desc>` instead of `<gloss>`?!

2022-01-05 14:20 UTC, sabineseifert commented on P5/Source/Specs/acquisition.xml
> +  <gloss xml:lang="de" versiondate="2021-10-24">enthält Informationen über den Vorgang, durch den ein Manuskript, ein Manuskriptteil oder ein anderes Objekt in den Besitz einer Institution gelangt is
It also should be `@versionDate` with an upper case 'D'.

2022-01-05 14:20 UTC, sabineseifert commented on P5/Source/Specs/actor.xml
> +  <desc versiondate="2021-10-25" xml:lang="de">enthält den Namen einer Schauspielerin oder eines Schauspielers, der in einer Besetzungsliste aufscheint.</desc>
It should be `@versionDate` with an upper case 'D'.

2022-01-05 14:20 UTC, sabineseifert commented on P5/Source/Specs/annotation.xml
> +  <desc versiondate="2021-10-21" xml:lang="de" versionDate="2021-10-21">repräsentiert eine Annotation die dem <ref target="#WADM">Web Annotation Data Model</ref>.</desc>
There are two `@versionDate` attributes: one with upper case 'D', the other with lower case 'd'.

2022-01-05 14:20 UTC, sabineseifert commented on P5/Source/Specs/annotation.xml
> +  <desc versiondate="2021-10-21" xml:lang="de" versionDate="2021-10-21">repräsentiert eine Annotation die dem <ref target="#WADM">Web Annotation Data Model</ref>.</desc>
There is a comma missing after "Annotation" and there is also a verb missing at the end of the sentence, something like "folgt".

2022-01-05 15:34 UTC, martinascholger commented
I think this was an early test with the translation tool. I think we should decline this PR and create a new one.

2022-01-19 10:33 UTC, sabineseifert commented
Closing since this was a test for the translation tool.

2022-01-19 10:33 UTC, closed without merging