Translation from Carmen-Grijalba/TEI
TEIC/TEI pull request #2234
Opened 2022-02-20 10:49 UTC by Carmen-Grijalba

2022-06-02 14:56 UTC, sabineseifert commented
Merged dev branch into pull request to resolve conflicts. Ready to review for @HelenaSabel. :-)

2022-06-03 07:00 UTC, HelenaSabel requested changes
I left some suggestions that should be commited before merging (some are stylistic, but others concern translation issues and typos)

2022-06-03 07:00 UTC, HelenaSabel commented on P5/Source/Specs/unclear.xml
> +          <gloss xml:lang="es" versionDate="2022-02-20">conducto excéntrico</gloss>
```suggestion
          <gloss xml:lang="es" versionDate="2022-06-03">ductus excéntrico</gloss>
```

2022-06-03 07:00 UTC, HelenaSabel commented on P5/Source/Specs/unclear.xml
> +  <remarks versionDate="2022-02-20" xml:lang="es"><p>El mismo elemento se usar para todos los casos de incertidubre en la transcripción del contenido de un elemento, para material tanto escrito como
```suggestion
  <remarks versionDate="2022-02-20" xml:lang="es"><p>El mismo elemento se usa para todos los casos de incertidubre en la transcripción del contenido de un elemento, para material tanto escrito como hablado. Para otros aspectos relacionados con la certeza, incertidumbre y fiablilidad del etiquetado y transcripción, consultar el capítulo <ptr target="#CE"/>.</p>
```

2022-06-03 07:00 UTC, HelenaSabel commented on P5/Source/Specs/unclear.xml
> +    <p>El atributo <att>hand</att> dirige a una definición de la mano impliciada, más discutido en la sección <ptr target="#PHDH"/>.</p></remarks>
```suggestion
    <p>El atributo <att>hand</att> dirige a una descripción de la mano implicada; se discute de manera más detallada en la sección <ptr target="#PHDH"/>.</p></remarks>
```

2022-06-29 07:47 UTC, merged