Translation from CarmendeSantiago/TEI
TEIC/TEI pull request #2245
Opened 2022-03-16 20:48 UTC by CarmendeSantiago

2022-04-10 14:19 UTC, HelenaSabel requested changes
There were small issues in the translation and I added suggestions with the changes that need to be accepted before merging,

2022-04-10 14:19 UTC, HelenaSabel commented on P5/Source/Specs/abbr.xml
> +          <gloss xml:lang="es" versionDate="2022-03-16">la abreviatura se emplea para un
```suggestion
          <gloss xml:lang="es" versionDate="2022-03-16">la abreviatura se emplea para una
```

2022-04-10 14:19 UTC, HelenaSabel commented on P5/Source/Specs/abbr.xml
> +tratamiento en la dirección (el Dr.,, Sr.,…)</gloss>
```suggestion
fórmula de tratamiento (Dr, Dra, Sra, Sr, …)</gloss>
```

2022-04-10 14:19 UTC, HelenaSabel commented on P5/Source/Specs/abbr.xml
> +          <gloss xml:lang="es" versionDate="2022-03-16">la abreviatura proporciona a las
```suggestion
          <gloss xml:lang="es" versionDate="2022-03-16">la abreviatura proporciona las
```

2022-10-25 07:34 UTC, rettinghaus commented
I think all these `gloss` should be `desc`.

2023-01-13 01:24 UTC, sydb commented
Even though my Spanish is _way_ too weak to contribute meaningfully, I think @rettinghaus is correct — these should probably be descriptions, not glosses. Except that `@type` of `<abbr>` _already has_ a gloss in Spanish (“tipo”), and it _already has_ a description in Spanish, that looks suspiciously like the glosses provided on this PR. Has someone already fixed this and not closed the PR?

2023-05-08 19:29 UTC, HelenaSabel commented
There was confusion between `<desc>` and `<gloss>` and the translation could be improved a bit (like trying to not use the so called “generic masculine”. Thus, we decided to just close this PR.

2023-05-08 19:29 UTC, closed without merging