Updated gloss of pb, lb, cb in French
TEIC/TEI pull request #2288
Opened 2022-04-25 13:49 UTC by sabineseifert

#2241

2022-04-26 10:22 UTC, peterstadler requested changes

2022-04-26 10:22 UTC, peterstadler commented on P5/Source/Specs/cb.xml
> +  <gloss versionDate="2009-01-06" xml:lang="fr">début de colonne</gloss>
when changing a description (or gloss) you must also update the corresponding `@versionDate` attribute (to the current date) on that element.

2022-05-12 14:07 UTC, peterstadler approved these changes
looks great, thank you :)

2022-05-12 15:01 UTC, HelenaSabel requested changes
I added the Spanish translations of certain `<desc>` elements that needed to be updated, and I added some comments concerning the update of the `@versionDate` of French `<desc>` elements when no changes seemed to be made in the contents of the translation...

2022-05-12 15:01 UTC, HelenaSabel commented on P5/Source/Specs/cb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le
It seems that the contents of this `<desc>` element haven’t been changed in this PR, so in principle, the original date should remain. However, considering that this French description is a literal translation of the current English version, I agree that the date could be updated so it isn’t flagged as an out-of-date translation.

2022-05-12 15:01 UTC, HelenaSabel commented on P5/Source/Specs/cb.xml
>    <desc versionDate="2007-05-04" xml:lang="es">indica la frontera entre una columna de un texto y la siguiente en un sistema de referencia estándard.</desc>
```suggestion
  <desc versionDate="2022-05-12" xml:lang="es">indica el inicio de una nueva columna de texto en una página divida en columnas .</desc>
```

2022-05-12 15:01 UTC, HelenaSabel commented on P5/Source/Specs/lb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le début d'une nouvelle ligne (typographique) dans
In this case, the original date is already more recent than the English version. Considering that no changes were made, I wouldn’t update the date.

2022-05-12 15:01 UTC, HelenaSabel commented on P5/Source/Specs/pb.xml
>    <desc versionDate="2007-05-04" xml:lang="es">marca la frontera entre una página de un texto y la
```suggestion
  <desc versionDate="2022-05-12" xml:lang="es">marca el inicio de una nueva página de un texto
```

2022-05-12 15:01 UTC, HelenaSabel commented on P5/Source/Specs/pb.xml
>      siguiente en un sistema de referencia estándard.</desc>
```suggestion
    en un documento paginado.</desc>
```

2022-05-13 06:32 UTC, peterstadler commented on P5/Source/Specs/cb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le
I was working on this with @sabineseifert so I take the liberty to respond: 
Yes, the intention was to flag this `<desc>` as "approved on 2022-05-12", not as "changed on 2022-05-12".

2022-05-13 06:35 UTC, peterstadler commented on P5/Source/Specs/lb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le début d'une nouvelle ligne (typographique) dans
Yes, you're right that this change was unnecessary – yet it doesn't hurt. I wonder how @hcayless translation tool deals with such cases. Are you able to only "approve" a translation without altering it?

2022-05-13 06:58 UTC, HelenaSabel commented on P5/Source/Specs/lb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le début d'une nouvelle ligne (typographique) dans
Thank you for the answers, @peterstadler. I am going to delete the suggestion of keeping the previous date and update my review.

2022-05-13 06:59 UTC, HelenaSabel approved these changes

2022-05-13 11:09 UTC, peterstadler commented on P5/Source/Specs/lb.xml
> +  <desc versionDate="2022-05-12" xml:lang="fr">marque le début d'une nouvelle ligne (typographique) dans
Well, you made a very valid point and your review was technically great (in providing the code), too!
I was just trying to give some background on how we got there. So, please let's pull in your improvements!

2022-08-18 08:39 UTC, merged