Update encoding of examples
TEIC/TEI pull request #2375
Opened 2022-11-30 11:16 UTC by sabineseifert

Reorganized encoding of `cl` as the relative clause is only the first part of the sentence and not the whole sentence. This way, the encoding of `l` could also be added in the English example.
For the French example, reorganized encoding of `cl` as the relative clause and moved type and function attributes.
Could not check or update example in zh-TW due to lack of language skills.

2022-12-21 09:48 UTC, peterstadler commented
pinging @HelenaSabel for review ;)

2022-12-26 15:26 UTC, HelenaSabel requested changes
I added a suggestion concerning the French example: with a relative clause, I think the `<cl>` elements must be nested (it seems incorrect to me to have a clause segmentation that has the antecedent and the relative in two different clauses, but with no hierarchy).

2022-12-26 15:26 UTC, HelenaSabel commented on P5/Source/Specs/cl.xml
> +      <cl type="relative" function="proposition_relative_déterminative">qui viennent.</cl>
```suggestion
      <cl>Il nous rejoindra dans
          les jours
      <cl type="relative" function="proposition_relative_déterminative">qui viennent.</cl>
      </cl>
```

2023-01-11 10:35 UTC, peterstadler commented
Thanks @HelenaSabel for the review! @sabineseifert  pulled in your suggestion and I think this is ready to be merged now

2023-01-11 10:35 UTC, merged