make att.namespaceable sensible
TEIC/TEI pull request #2397
Opened 2023-02-13 22:47 UTC by sydb

Update wording of description & add remarks per #2395.

This does not (IMHO) require either 3 reviews or 3 assignees — as soon as 1 reviewer gives OK, one of the assignees should merge (presuming they agree).

2023-02-14 04:20 UTC, joeytakeda requested changes
With the exception of a tiny typo, this looks good to me

2023-02-14 04:20 UTC, joeytakeda commented on P5/Source/Specs/att.namespaceable.xml
> +        children fo the <gi>schemSpec</gi>, <emph>unless</emph>
teeny typo: "fo" --> "of" :-)

2023-02-14 04:55 UTC, sydb commented on P5/Source/Specs/att.namespaceable.xml
> +        children fo the <gi>schemSpec</gi>, <emph>unless</emph>
Good catch, thanks!

2023-03-11 15:43 UTC, martindholmes approved these changes
This looks good to me. No problems with merging.

2023-03-19 20:05 UTC, merged