Deprecated the `<re>` element
TEIC/TEI pull request #2521
Opened 2024-01-10 18:26 UTC by trishaoconnor

Deprecated the `<re>` element for #2487 and in examples replaced `<re>` with `<entry>` element with the `@type` set to "relatedEntry".

2024-01-19 07:34 UTC, laurentromary commented
I have checked this pull request and it all seems like we want it. Thanks!

2024-01-21 11:39 UTC, HelenaSabel requested changes
My first comment concerns commit 61247e54d5412e5f1a2e46adb76ef92879c66b3a: I think it might have been included in this PR by mistake.

Then I made a suggestion so that the recommended value for `@type` in the deprecation note matches the examples. @trishaoconnor: if you agree you can click on “commit suggestion” :)

2024-01-21 11:39 UTC, HelenaSabel commented on P5/Source/Specs/re.xml
> +      <val>related</val> instead.</desc>
```suggestion
      <val>relatedEntry</val> instead.</desc>
```

2024-01-22 09:43 UTC, trishaoconnor commented
Thank you @HelenaSabel for spotting these mistakes. My apologies for not recognising that the commit was added to this PR. That was an accident.  I have clicked "commit suggestion" so the deprecation note now matches the examples.

2024-01-22 18:21 UTC, HelenaSabel commented
@trishaoconnor: do you want to try to delete commit https://github.com/TEIC/TEI/commit/61247e54d5412e5f1a2e46adb76ef92879c66b3a? I think you could try:
```
git revert --strategy resolve 61247e54d5412e5f1a2e46adb76ef92879c66b3a
```
That will delete the commit (without altering the history). But if @sydb, who is assigned to this PR, thinks is ok to merge as it is, fine with me :)

2024-01-26 14:28 UTC, sydb commented
Yes, the global addition of `mode="add"` was added to this PR by mistake. But since it is a separate commit, and has no effect on anything anyway, I would just not worry about it. (Except to _avoid_ a “squash and merge”.)
But that may just be me being lazy — feel free to separate to a separate PR if y’all think it important.

2024-01-26 14:36 UTC, sydb commented
An attempt to ping @GusRiva on the TEI repo. Please ignore.

2024-01-26 16:02 UTC, HelenaSabel approved these changes

2024-01-26 16:04 UTC, merged