section of CMC `<post>` tagdoc mis-encoded
TEIC/TEI pull request #2573
Opened 2024-07-09 21:39 UTC by sydb

This addresses #2571.

2024-07-09 21:46 UTC, ebeshero commented
Adding @joeytakeda to the reviewer list since he and I were concerned about the definition of `@replyTo` in reviewing the CMC chapter...

2024-07-09 21:59 UTC, ebeshero requested changes

2024-07-09 21:59 UTC, ebeshero commented on P5/Source/Specs/post.xml
> +	<p>This attribute should be used to encode <q>technical</q>
Noting that a portion is removed here. The description of `@replyTo` used to begin thus: "indicates to which post the current post replies or refers to". I suppose by removing it, we are moving some specific constraint on how people could apply this attribute, since it could now contain any "`<q>technical</a>` reply information ", and I'm not quite sure what that could mean. (Does it mean we indicate a button was pushed?) Before it seemed clearer that this was meant to be a pointer to a previous post to which this is a reply.  I think maybe we should put the indicator phrasing back. @sydb

2024-07-09 22:01 UTC, ebeshero commented on P5/Source/Specs/post.xml
> +	<p>This attribute should be used to encode <q>technical</q>
I do like the new phrasing of the next sentence, though re "<q>technical</q> reply information". But I don't think it stands on its own as a leading sentence in the description of `@replyTo`.

2024-07-10 01:56 UTC, sydb commented on P5/Source/Specs/post.xml
> +	<p>This attribute should be used to encode <q>technical</q>
No, nothing (substantive) has been removed. Yes, the **description** used to begin “indicates to which post the current post replies or refers _to_” and now it **is** “indicates to which post the current post replies or refers” (the only difference is I dropped the word “to” from the end).
All the other stuff has been _moved_ (not _removed_) from the **description** to the **remarks**, where it belongs. But it also has not been changed substantively. It used to read “This attribute should … discourse markers or the indentation relations in Wiki talk pages.” and now instead reads “This attribute should … discourse markers or indentation.”.

2024-07-15 10:59 UTC, peterstadler approved these changes
This looks good to me, i.e. the PR fixes what the ticket complains about

2024-07-15 11:01 UTC, peterstadler commented on P5/Source/Specs/post.xml
> +	<p>This attribute should be used to encode <q>technical</q>
Agree with @syd here that it's just a moving of text parts without substantial changes

2024-07-15 11:02 UTC, peterstadler commented
This could go into the 4.8.1 ? Should the milestone for the ticket and PR be adjusted accordingly?

2024-09-02 05:00 UTC, ebeshero commented on P5/Source/Specs/post.xml
> +	<p>This attribute should be used to encode <q>technical</q>
Okay, no need to change it back, then. Sorry for missing the move to remarks.

2024-09-02 05:00 UTC, ebeshero approved these changes

2024-09-02 05:02 UTC, merged