Reformulated remark for xmlns in root elements (TEI and teiCorpus)
TEIC/TEI pull request #2632
Opened 2024-12-10 14:39 UTC by GusRiva

This is to close issue #2621 
Modifies the prose of the remark for TEI and teiCorpus. I slightly reformulated the suggestion from @sydb in the issue and added a Spanish translation as well.

2024-12-19 03:22 UTC, sydb requested changes
Looks good to me, save two tiny typos. But I only looked at the English; leaving the Spanish review to @HelenaSabel.

2024-12-19 03:22 UTC, sydb commented on P5/Source/Specs/TEI.xml
> +     in the TEI namespace (See <ptr target="#SGname"/>). Thus, when it is used as the
s/See/see/;

2024-12-19 03:22 UTC, sydb commented on P5/Source/Specs/teiCorpus.xml
> +      in the TEI namespace (See <ptr target="#SGname"/>). Thus, when it is used as the
s/See/see/;

2024-12-19 08:40 UTC, GusRiva commented
> Looks good to me, save two tiny typos. But I only looked at the English; leaving the Spanish review to @HelenaSabel.

Thanks! Corrected the typo in https://github.com/TEIC/TEI/pull/2632/commits/4658cf1a6cd1dff048e9d080c4ed314934ec5486

2025-01-20 18:57 UTC, sydb approved these changes
Approving for the English portions. My Spanish is not good enough to qualify me to review the Spanish paragraph.

2025-01-21 14:37 UTC, HelenaSabel requested changes
I suggested a few changes related to the Spanish translation of _namespace_ (which, in my opinion should always be _espacio de nombres_)

2025-01-21 14:37 UTC, HelenaSabel commented on P5/Source/Specs/TEI.xml
> +    <p>Como todos los elementos en el esquema TEI (excepto <gi>egXML</gi>), este elemento se encuentra en el espacio de nombre (<foreign>namespace</foreign>) de TEI (cf. <ptr target="#SGname"/>). Por
```suggestion
    <p>Como todos los elementos en el esquema TEI (excepto <gi>egXML</gi>), este elemento se encuentra en el espacio de nombres (<foreign>namespace</foreign>) de TEI (cf. <ptr target="#SGname"/>). Por lo tanto, cuando se utiliza como el elemento más externo de un documento TEI, es necesario especificar el espacio de nombres de TEI en su interior. Esto se hace, normalmente, incluyendo <ident type="ns">http://www.tei-c.org/ns/1.0</ident> como valor de la declaración de espacio de nombres (xmlns) sin indicar un prefijo, y por lo tanto sin necesidad de utilizar un prefijo en los elementos TEI del resto del documento. Por ejemplo: <tag type="start">TEI version="4.8.1" xml:lang="it" xmlns="http://www.tei-c.org/ns/1.0"</tag>.</p></remarks>
```

2025-01-21 14:37 UTC, HelenaSabel commented on P5/Source/Specs/teiCorpus.xml
> +    <p>Como todos los elementos en el esquema TEI (excepto <gi>egXML</gi>), este elemento se encuentra en el espacio de nombre (<foreign>namespace</foreign>) de TEI (cf. <ptr target="#SGname"/>). Por
```suggestion
    <p>Como todos los elementos en el esquema TEI (excepto <gi>egXML</gi>), este elemento se encuentra en el espacio de nombres (<foreign>namespace</foreign>) de TEI (cf. <ptr target="#SGname"/>). Por lo tanto, cuando se utiliza como el elemento más externo en un documento TEI, es necesario especificar el espacio de nombres de TEI en su interior. Esto se hace, normalmente, incluyendo <ident type="ns">http://www.tei-c.org/ns/1.0</ident> como valor de la declaración del espacio de nombres (xmlns) sin indicar un prefijo, y por lo tanto sin necesidad de utilizar un prefijo en los elementos TEI del resto del documento. Por ejemplo: <tag type="start">teiCorpus version="4.8.1" xml:lang="es" xmlns="http://www.tei-c.org/ns/1.0"</tag>.</p></remarks>
```

2025-01-21 16:03 UTC, trishaoconnor commented
This looks OK to merge to me, reviewer comments from @sydb and @HelenaSabel have been applied.

2025-01-21 16:03 UTC, merged