Replaced 'break' with 'beginning' for page|line|column|gathering in Guidelines and Specs
TEIC/TEI pull request #2634
Opened 2024-12-10 21:27 UTC by trishaoconnor

Replaced 'break' with 'beginning' for page|line|column|gathering in the following files from the Guidelines and Specs:

```
-     page beginning (<pb>)
-     column beginning (<cb>)
-     att.breaking
-     parameter (<param>)
-     model (<model>)
-     att.edition
-     att.milestoneUnit
-     WD Non Standard Characters
-     SG Gentle Introduction
-     PH Primary Sources
-     NH Non Hierarchical
-     HD Header
-     FT Tables Formulae Graphics
-     DS Default Text Structure
-     DI Print Dictionaries
-     CO Core Elements
-     CH Language Character Sets
```

There were no mentions of 'break' in the prose of <gb> but I deleted an superfluous space in the prose

The requested changes to `<lb>` are addressed in PR https://github.com/TEIC/TEI/pull/2633.

2025-01-12 00:24 UTC, ebeshero commented
@sydb Might as well have a look at this while you're at it?

2025-01-13 00:15 UTC, sydb requested changes
The majority of my suggestions for change, here, are underpinned by my strong distaste for using the noun “beginning” unless it is being used to gloss an element itself or very specifically about the beginning of a feature. Others may disagree.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CH-LanguagesCharacterSets.xml
> -   points line breaks might occur and so forth.  </p>
This use of the term has nothing to do with our `<lb>` element, and perhaps should just be left as “break”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -lexicalized. Any case where the word is hyphenated across a linebreak,
This use of the term has nothing to do with our `<lb>` element, and perhaps should just be left as “line break”. (Note the space — 18 of the 25 occurences of "line.?break" in the _Guidelines_ have a space. (One has a hyphen, and six have the single word version.)

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
>  pagination, etc of a source document, since the encoder should not
Missing period after “etc”. (I know that has nothing to do with the changes @trishaoconnor is making, but since I noticed it …)

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +outlined in this section.  Retaining page beginnings in the markup is also
I would use “boundaries” as opposed to either “breaks” or “beginnings”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -own. Line breaks in prose texts may be, but need not be, tagged.<note place="bottom">Many encoders find it convenient to retain the line
I would leave as “break”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -breaks of the original during data entry, to simplify proofreading,
I would leave as “break”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +  but this may be done without inserting a tag for each line beginning of
I think this was correctly changed to “beginning”, but am inclined to use “an element” instead of “a tag”. (For starters, it is allowed in XML to represent that element with two tags: `<lb></lb>`, although admittedly no one does that.)

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +  Where hyphenation appears before a line or page beginning, the encoder may
“Where hyphenation appears at the end of a topographic line, a column, or a  page, the encoder may” would be better, no?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +interrupted by a typographic line beginning, the encoder may choose to
I would leave as “break”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +two typographic lines, with a beginning at the point indicated. Note that
Perhaps “with the second beginning at the point indicated”?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +    lines in non-verse materials: if the line-beginninging points in a prose
Perhaps “… if the lineation of a prose text is considered …”?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/DI-PrintDictionaries.xml
> +  two-dimensional printed page, including information about line and page beginnings
Perhaps “including information about lineation, pagination, and other features of layout”?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/DI-PrintDictionaries.xml
> +  would be preserved, but the fact of the line beginning would not. Font shifts might
Perhaps “… would be preserved, but the fact that the word was split across a line break with a <soCalled>soft</soCalled> hyphen would not”?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/DS-DefaultTextStructure.xml
> +  Note that if the page beginnings in the original source have also been
Could be left as is (with “beginnings”, which is a bit clumsy) or perhaps something like “Note that if the pagination of the original source has also been explicitly encoded and given identifiers, the references to them in the above …”

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/FT-TablesFormulaeGraphics.xml
> +        allow beginnings to be signalled inside tables; <gi>figure</gi> provides an
I think something like “allow new columns or lines to be signalled …” would be preferable.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/PH-PrimarySources.xml
> +               spaces, lines, page and line beginnings, changes of manuscript hand, etc. (section <ptr target="#PHPH"/>)</item>
I think that the adjective “unusual” is intended to modify only the word “spaces”. Thus I think we should use something like “methods of describing important extra-linguistic phenomena in the source: pagination, lineation, unusual spaces, changes of manuscript hand, etc.”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/PH-PrimarySources.xml
>           where the a non-embedded transcription has been provided, using the <gi>text</gi> element,
I am not sure if the 2nd word on this line should be the definite article “the” or the indefinite article “a”, but we certainly don’t want both! (I know that has nothing to do with the changes @trishaoconnor is making, but since I noticed it …)

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> +typeface, line beginnings, use of whitespace and so forth.</p>
Perhaps “such as typeface, original topographic lineation, use of whitespace …”?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> -Whitespace and line breaks have been added to the example for the
I think this one should remain “breaks”, or perhaps be re-written “Whitespace, including newline characters, have been added …”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> -determine where to begin a new page of output. Page-breaking decisions
I would leave this one as “breaking”, or re-word to “It is generally best to leave pagination of the output to the formatting engine alone, …”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
> +    in the sense of poetic lines; the text is continuous prose, and line beginnings
Perhaps “… continuous prose, and division into separate lines is incidental.” or some such?

2025-01-13 00:15 UTC, sydb commented on P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
> + boustrophedon. In the inscription above, some words run across line beginnings,
I think “some words are split across two lines,” would be better.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Specs/att.breaking.xml
> +      line beginnings occur in the middle of the words <mentioned>lāðost</mentioned>
I think something like
~~~xml
    <p>In the following lines from the <title level="a">Dream of the Rood</title>, 
      the words <mentioned>lāðost</mentioned> and <mentioned>reord-berendum</mentioned>
      each start on one line and continue on the next.</p>
~~~
would be better.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Specs/model.xml
> -          <desc versionDate="2015-08-21" xml:lang="en">create a line, column, or page break
IMOm, this should be left “break”.

2025-01-13 00:15 UTC, sydb commented on P5/Source/Specs/param.xml
> -            categorize the specified behaviour in any way; for example the kind of break (when used
I think this should remain “break”.

2025-01-13 23:07 UTC, martindholmes commented
@trishaoconnor Just letting you know I've just cherry-picked a single-character commit fix from dev into this branch just to make sure it didn't cause any issues. It was a typo in the boustrophedon section of WD-NonStandardCharacters.xml which just needed an added s, found by @sydb. Doesn't affect any of the other stuff in your branch.

2025-01-16 12:38 UTC, trishaoconnor commented
Thank you very much @sydb for your thorough review and thank you too @martindholmes for fixing that typo and merging it to the PR. 

I appreciate your point @sydb and thank you very much for highlighting the passages where "beginning" isn't an appropriate substitution for "break". I confess that I still have a preference for using "beginning" instead of "break" and would be in favour of rewriting these passages along similar lines to the example that you supplied above: 

`<p>In the following lines from the <title level="a">Dream of the Rood</title>, 
      the words <mentioned>lāðost</mentioned> and <mentioned>reord-berendum</mentioned>
      each start on one line and continue on the next.</p>`
 
Of course, if the general consensus is to revert to "break" instead, I'll happily do so.

2025-01-16 13:13 UTC, trishaoconnor commented on P5/Source/Specs/att.breaking.xml
> +      line beginnings occur in the middle of the words <mentioned>lāðost</mentioned>
Thank you very much, I've updated the file with your recommended changes.

2025-01-16 13:18 UTC, trishaoconnor commented on P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
> + boustrophedon. In the inscription above, some words run across line beginnings,
Agreed. I've applied the above change.

2025-01-16 13:20 UTC, trishaoconnor commented on P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
> +    in the sense of poetic lines; the text is continuous prose, and line beginnings
Updated to “… continuous prose, and the division into separate lines is incidental.”

2025-01-16 13:34 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CH-LanguagesCharacterSets.xml
> -   points line breaks might occur and so forth.  </p>
How would you feel about rewriting the above without "break" but with "divisions" instead? 

> "... at which point line divisions might occur and so forth"

2025-01-16 16:46 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -lexicalized. Any case where the word is hyphenated across a linebreak,
Further down on line 353, "line division" is used. For consistency, I've rewritten line 332 using "division" instead of "beginning" and "break". Hopefully, this substitution is acceptable? 

> "Any case where the word is hyphenated across a linebreak..."

Thank you very much, too, for spotting the different renderings of the term throughout the Guidelines.

2025-01-16 16:53 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
>  pagination, etc of a source document, since the encoder should not
Thank you for spotting this! Missing period is added now.

2025-01-16 16:55 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +outlined in this section.  Retaining page beginnings in the markup is also
Excellent suggestion. Thank you.

2025-01-16 17:08 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -breaks of the original during data entry, to simplify proofreading,
Rewrote this using "divisions" instead of "breaks"

2025-01-16 17:09 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +  but this may be done without inserting a tag for each line beginning of
Excellent point. I've rewritten this to include "an element" instead of "a tag" but also changed "tagged" with "encoded" and "of the original" to "in the original". 

> `"Line divisions in prose texts may be, but need not be, encoded.<note place="bottom">Many encoders find it convenient to retain the line
>   divisions of the original during data entry, to simplify proofreading,
>   but this may be done without inserting an element for each line beginning in
> the original."`

2025-01-16 17:16 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +  Where hyphenation appears before a line or page beginning, the encoder may
Agreed. Updated accordingly.

2025-01-16 17:21 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +interrupted by a typographic line beginning, the encoder may choose to
What about "interrupted by the beginning of a new typographic line,..." ?

2025-01-16 18:00 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +two typographic lines, with a beginning at the point indicated. Note that
Thank you. Updated accordingly now.

2025-01-16 18:06 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> +    lines in non-verse materials: if the line-beginninging points in a prose
Thank you so much for catching this embarrassing typo!

I've updated to: "if the lineation of a prose text is considered important for analysis, the beginning of each line should be marked with..."

2025-01-16 18:12 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -own. Line breaks in prose texts may be, but need not be, tagged.<note place="bottom">Many encoders find it convenient to retain the line
I've rewritten the above using "divisions" instead of "breaks" or "beginnings"

2025-01-16 19:20 UTC, trishaoconnor commented on P5/Source/Guidelines/en/DI-PrintDictionaries.xml
> +  two-dimensional printed page, including information about line and page beginnings
Thank you for the great suggestions. Updated accordingly.

2025-01-16 19:26 UTC, trishaoconnor commented on P5/Source/Guidelines/en/DI-PrintDictionaries.xml
> +  would be preserved, but the fact of the line beginning would not. Font shifts might
I've rewritten the above as "...but the fact that the word was split across two lines with a soft hyphen would not".

2025-01-16 19:32 UTC, trishaoconnor commented on P5/Source/Guidelines/en/DS-DefaultTextStructure.xml
> +  Note that if the page beginnings in the original source have also been
I much prefer your suggestion. That's updated now.

2025-01-16 19:38 UTC, trishaoconnor commented on P5/Source/Guidelines/en/FT-TablesFormulaeGraphics.xml
> +        allow beginnings to be signalled inside tables; <gi>figure</gi> provides an
Agreed and done. Thanks for the suggested text. It's clearer than the original.

2025-01-16 19:50 UTC, trishaoconnor commented on P5/Source/Guidelines/en/PH-PrimarySources.xml
>           where the a non-embedded transcription has been provided, using the <gi>text</gi> element,
Oh, dear! Well spotted. Thank you for highlighting this. I've deleted the definite article. Also, I added the missing punctuation to etc on line 2554.

2025-01-16 19:56 UTC, trishaoconnor commented on P5/Source/Guidelines/en/PH-PrimarySources.xml
> +               spaces, lines, page and line beginnings, changes of manuscript hand, etc. (section <ptr target="#PHPH"/>)</item>
I think so too, I've rewritten the sentence according to your suggestion. Thank you.

2025-01-16 20:06 UTC, trishaoconnor commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> -Whitespace and line breaks have been added to the example for the
Would "line divisions" work here instead?

2025-01-16 20:10 UTC, trishaoconnor commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> -determine where to begin a new page of output. Page-breaking decisions
I prefer your proposed rewording. Thank you!

2025-01-16 20:21 UTC, trishaoconnor commented on P5/Source/Specs/param.xml
> -            categorize the specified behaviour in any way; for example the kind of break (when used
Reverted to "break" but I'm curious if you think that "division" would have also been a satisfactory substitution.

2025-01-16 20:22 UTC, trishaoconnor commented on P5/Source/Specs/model.xml
> -          <desc versionDate="2015-08-21" xml:lang="en">create a line, column, or page break
Changed back to "break"

2025-01-17 01:40 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -lexicalized. Any case where the word is hyphenated across a linebreak,
Seems fine. But with respect to the different renderings of the term, no pat on the back for just _finding_ them; I have not gone out and _fixed_ them, yet. :smile:

2025-01-17 01:52 UTC, sydb commented on P5/Source/Guidelines/en/CH-LanguagesCharacterSets.xml
> -   points line breaks might occur and so forth.  </p>
Ooh, I like that; but I think I would like a more complete re-write better:

> It might nevertheless be helpful to put some of the terminology used for the rendering process in the context of the discussion of this chapter. As was mentioned above, Unicode encodes abstract characters, not specific glyphs. For any process that makes characters visible, however, concrete, specifically designed glyph shapes have to be used. For a printing process, for example, these shapes describe exactly at which point ink has to be put on the paper and which areas have to be left blank. If we want to print a character from the Latin script, besides the selection of the overall glyph shape, this process also requires that a specific weight and size of the font has been selected, and to what degree the shape should be slanted. Beyond individual characters, the overall typesetting process also needs to follow specific rules for calculating the distance between characters, for determining how much whitespace occurs between any two words, and how long each line should be (and thus at which points a new line begins), and so forth.

(Feel free to ignore, use, or tweak.)

2025-01-17 02:06 UTC, sydb commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> +typeface, line beginnings, use of whitespace and so forth.</p>
Right, but neither of us noticed that we still need the Oxford comma after “whitespace”.

2025-01-17 02:10 UTC, sydb commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> -Whitespace and line breaks have been added to the example for the
Yup, works.

2025-01-17 02:13 UTC, sydb commented on P5/Source/Specs/param.xml
> -            categorize the specified behaviour in any way; for example the kind of break (when used
Yes, I guess “division” is OK, but the behavior being discussed is, after all, the "break" behavior.

2025-01-20 09:49 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CH-LanguagesCharacterSets.xml
> -   points line breaks might occur and so forth.  </p>
I like this. Thank you very much for taking the time to re-write the section.

2025-01-20 09:55 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -lexicalized. Any case where the word is hyphenated across a linebreak,
I searched using the query that @martinascholger kindly provided when opening the issue. I thought that this would have caught every instance, including variations between line-break, line break and linebreak?
`(page|line|column|gathering)[\s-]*breaks`
I'll search for the occurrences that you found an fix them too. :)

2025-01-20 09:58 UTC, trishaoconnor commented on P5/Source/Guidelines/en/SG-GentleIntroduction.xml
> +typeface, line beginnings, use of whitespace and so forth.</p>
Well spotted! Thank you. I've updated that now.

2025-01-20 10:49 UTC, trishaoconnor commented on P5/Source/Specs/param.xml
> -            categorize the specified behaviour in any way; for example the kind of break (when used
My apologies, I realised that it was the break behaviour being discussed after I had posted the above comment.  I've reverted "beginning" to "break". (I had meant to return and edit or delete the earlier comment but forgot).

2025-01-20 11:24 UTC, trishaoconnor commented on P5/Source/Guidelines/en/CO-CoreElements.xml
Line 2699 : Changed "linebreaks" to "line divisions"

`<item><term>inline</term> (items rendered within continuous prose, with no line divisions)</item>`

2025-01-20 14:59 UTC, sydb commented on P5/Source/Guidelines/en/CO-CoreElements.xml
> -lexicalized. Any case where the word is hyphenated across a linebreak,
Depends on what regular expression language you are using, I think. (I am not sure on this, but I think in most languages “\s”, when inside square brackets, means “whitespace”; but in some languages means “an ‘s’”. It would be quite conceivable that it means “a backslash or an ‘s”’, too.)

2025-01-20 16:28 UTC, sydb approved these changes

2025-01-20 19:09 UTC, merged

2025-01-20 19:09 UTC, ebeshero commented
I'm just merging this now, as it's ready to go for the release.