Changed gloss and desc for msName
TEIC/TEI pull request #2645
Opened 2024-12-23 11:07 UTC by sabineseifert

according to suggestions by @jamescummings and @sydb. 

I also added German translation.

closes #2434

Perhaps someone might update the Spanish, Italian etc.?

2024-12-23 16:20 UTC, sydb approved these changes
Overall looks great. I would prefer “as opposed to a” instead of “instead of any” in 
> … other object, instead of any formal identification number …

(Approving, because even without this suggested tweak, this is an improvement.)

2024-12-27 09:50 UTC, sabineseifert commented
Updated description in `<desc>` according to @sydb's suggestion :-)

2025-01-06 10:08 UTC, peterstadler requested changes

2025-01-06 10:08 UTC, peterstadler commented on P5/Source/Specs/msName.xml
> +  <desc versionDate="2024-12-23" xml:lang="de">enthält einen Eigennamen in Form eines Nomens oder einer Nominalphrase, der für ein Manuskript oder anderes Objekt verwendet wird, anstatt einer formale
Disclaimer: I'm a German native speaker but not a librarian 

```suggestion
  <desc versionDate="2024-12-23" xml:lang="de">enthält einen Eigennamen in Form eines Nomens oder einer Nominalphrase, der für ein Manuskript oder anderes Objekt verwendet wird, anstatt einer formalen Identifikationsnummer oder Signatur.</desc>
```

I would replace "Klassifikation" (de) with "Signatur" (de) here for the English term "classmark" (en) is more or a less a synonym of "shelfmark" (en) which is usually translated as "Signatur" (de). "Klassifikation" (de) on the other hand is "classification (scheme)" (en).

2025-01-13 19:48 UTC, martinascholger requested changes
I would also use "Signatur" instead of "Klassifikation"

2025-01-21 04:11 UTC, ebeshero commented
I've just applied the "Signatur" suggestion that @martinascholger and @peterstadler  agreed upon.

2025-01-21 04:23 UTC, ebeshero commented
Approving this PR because we've refined the prose edits. We can open a new ticket to update the gloss in other languages.

2025-01-21 04:23 UTC, merged